import pool from "@/lib/db";

let schemaReady: Promise<void> | null = null;

const statements = [
  `CREATE TABLE IF NOT EXISTS omni_projects (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    target_audience TEXT,
    brand_voice TEXT,
    legacy_client_id BIGINT,
    status TEXT NOT NULL DEFAULT 'active',
    telegram_chat_id TEXT,
    telegram_topic_id TEXT,
    created_by_telegram_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS omni_products (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES omni_projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    product_reference_notes TEXT,
    avatar_reference_notes TEXT,
    target_duration_seconds INTEGER NOT NULL DEFAULT 30,
    cta_mode TEXT NOT NULL DEFAULT 'article_in_description',
    cta_value TEXT,
    product_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    avatar_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS omni_client_avatars (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES omni_projects(id) ON DELETE CASCADE,
    display_name TEXT,
    prompt TEXT NOT NULL,
    reference_url TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    provider TEXT NOT NULL DEFAULT 'gpt-image-2',
    kie_character_id TEXT,
    kie_character_status TEXT,
    kie_character_payload JSONB,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS omni_telegram_topic_bindings (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES omni_projects(id) ON DELETE CASCADE,
    chat_id TEXT NOT NULL,
    topic_id TEXT NOT NULL,
    title TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(chat_id, topic_id)
  )`,
  `CREATE TABLE IF NOT EXISTS omni_legacy_scenario_links (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES omni_projects(id) ON DELETE CASCADE,
    product_id INTEGER REFERENCES omni_products(id) ON DELETE CASCADE,
    legacy_source TEXT NOT NULL DEFAULT 'old_db',
    legacy_scenario_id BIGINT NOT NULL,
    note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, product_id, legacy_source, legacy_scenario_id)
  )`,
  `CREATE TABLE IF NOT EXISTS omni_legacy_library_links (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES omni_projects(id) ON DELETE CASCADE,
    product_id INTEGER REFERENCES omni_products(id) ON DELETE CASCADE,
    legacy_client_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(project_id, product_id, legacy_client_id)
  )`,
  `CREATE TABLE IF NOT EXISTS omni_generated_scripts (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES omni_projects(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES omni_products(id) ON DELETE CASCADE,
    source_generated_script_id BIGINT,
    source_legacy_scenario_id BIGINT,
    source_legacy_client_id BIGINT,
    status TEXT NOT NULL DEFAULT 'draft',
    title TEXT,
    hook TEXT,
    script TEXT NOT NULL,
    caption TEXT,
    cta_keyword TEXT,
    lead_magnet TEXT,
    source_snapshot JSONB,
    product_snapshot JSONB,
    model TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS omni_reels (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES omni_projects(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES omni_products(id) ON DELETE CASCADE,
    source_legacy_scenario_id BIGINT,
    target_duration_seconds INTEGER NOT NULL,
    segment_count INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    brief TEXT,
    source_snapshot JSONB,
    product_snapshot JSONB,
    avatar_snapshot JSONB,
    creative_strategy JSONB,
    prompt_contract_version TEXT,
    stitch_status TEXT NOT NULL DEFAULT 'not_ready',
    final_video_url TEXT,
    final_s3_url TEXT,
    yandex_disk_path TEXT,
    yandex_public_url TEXT,
    yandex_status TEXT,
    yandex_error TEXT,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS omni_reel_segments (
    id SERIAL PRIMARY KEY,
    reel_id INTEGER NOT NULL REFERENCES omni_reels(id) ON DELETE CASCADE,
    segment_index INTEGER NOT NULL,
    duration_seconds INTEGER NOT NULL DEFAULT 10,
    slot_role TEXT,
    prompt TEXT,
    voiceover_text TEXT,
    creative_plan JSONB,
    prompt_validation JSONB,
    reference_url TEXT,
    kie_task_id TEXT,
    generation_provider TEXT NOT NULL DEFAULT 'cometapi',
    status TEXT NOT NULL DEFAULT 'draft',
    video_url TEXT,
    error_message TEXT,
    submitted_at TIMESTAMP,
    completed_at TIMESTAMP,
    request_payload JSONB,
    response_payload JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(reel_id, segment_index)
  )`,
  "ALTER TABLE omni_projects ADD COLUMN IF NOT EXISTS legacy_client_id BIGINT",
  "ALTER TABLE omni_projects ADD COLUMN IF NOT EXISTS target_audience TEXT",
  "ALTER TABLE omni_projects ADD COLUMN IF NOT EXISTS brand_voice TEXT",
  "ALTER TABLE omni_products ADD COLUMN IF NOT EXISTS cta_mode TEXT NOT NULL DEFAULT 'article_in_description'",
  "ALTER TABLE omni_products ADD COLUMN IF NOT EXISTS cta_value TEXT",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS source_snapshot JSONB",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS source_generated_script_id BIGINT",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS product_snapshot JSONB",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS avatar_snapshot JSONB",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS creative_strategy JSONB",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS prompt_contract_version TEXT",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS stitch_status TEXT NOT NULL DEFAULT 'not_ready'",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS final_s3_url TEXT",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS yandex_disk_path TEXT",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS yandex_public_url TEXT",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS yandex_status TEXT",
  "ALTER TABLE omni_reels ADD COLUMN IF NOT EXISTS yandex_error TEXT",
  "ALTER TABLE omni_client_avatars ADD COLUMN IF NOT EXISTS display_name TEXT",
  "ALTER TABLE omni_client_avatars ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE",
  "ALTER TABLE omni_client_avatars ADD COLUMN IF NOT EXISTS kie_character_id TEXT",
  "ALTER TABLE omni_client_avatars ADD COLUMN IF NOT EXISTS kie_character_status TEXT",
  "ALTER TABLE omni_client_avatars ADD COLUMN IF NOT EXISTS kie_character_payload JSONB",
  "ALTER TABLE omni_reel_segments ADD COLUMN IF NOT EXISTS slot_role TEXT",
  "ALTER TABLE omni_reel_segments ADD COLUMN IF NOT EXISTS voiceover_text TEXT",
  "ALTER TABLE omni_reel_segments ADD COLUMN IF NOT EXISTS creative_plan JSONB",
  "ALTER TABLE omni_reel_segments ADD COLUMN IF NOT EXISTS prompt_validation JSONB",
  "ALTER TABLE omni_reel_segments ADD COLUMN IF NOT EXISTS reference_url TEXT",
  "ALTER TABLE omni_reel_segments ADD COLUMN IF NOT EXISTS generation_provider TEXT NOT NULL DEFAULT 'cometapi'",
  "ALTER TABLE omni_reel_segments ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP",
  "ALTER TABLE omni_reel_segments ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP",
  `UPDATE omni_projects
   SET legacy_client_id = substring(description from 'legacy-client:([0-9]+)')::bigint
   WHERE legacy_client_id IS NULL
     AND description ~ '^legacy-client:[0-9]+$'`,
  "CREATE INDEX IF NOT EXISTS idx_omni_products_project ON omni_products(project_id)",
  "CREATE INDEX IF NOT EXISTS idx_omni_projects_legacy_client ON omni_projects(legacy_client_id)",
  "CREATE INDEX IF NOT EXISTS idx_omni_client_avatars_project ON omni_client_avatars(project_id, updated_at DESC)",
  "CREATE INDEX IF NOT EXISTS idx_omni_client_avatars_active ON omni_client_avatars(project_id, is_active, updated_at DESC)",
  "CREATE INDEX IF NOT EXISTS idx_omni_links_project ON omni_legacy_scenario_links(project_id)",
  "CREATE INDEX IF NOT EXISTS idx_omni_links_product ON omni_legacy_scenario_links(product_id)",
  "CREATE INDEX IF NOT EXISTS idx_omni_library_links_project ON omni_legacy_library_links(project_id)",
  "CREATE INDEX IF NOT EXISTS idx_omni_library_links_product ON omni_legacy_library_links(product_id)",
  "CREATE INDEX IF NOT EXISTS idx_omni_generated_scripts_project_product ON omni_generated_scripts(project_id, product_id, created_at DESC)",
  "CREATE INDEX IF NOT EXISTS idx_omni_generated_scripts_source ON omni_generated_scripts(source_legacy_scenario_id)",
  "CREATE INDEX IF NOT EXISTS idx_omni_reels_project_product ON omni_reels(project_id, product_id)",
  "CREATE INDEX IF NOT EXISTS idx_omni_reels_generated_script ON omni_reels(source_generated_script_id)",
  "CREATE INDEX IF NOT EXISTS idx_omni_segments_reel ON omni_reel_segments(reel_id, segment_index)",
];

export async function ensureOmniSchema() {
  if (!schemaReady) {
    schemaReady = (async () => {
      for (const statement of statements) {
        await pool.query(statement);
      }
    })();
  }

  return schemaReady;
}
